kind: pipeline
type: docker
name: kubeimooc-server-publish
steps:
  - name: build
    image: plugins/docker
    volumes:
      - name: hosts
        path: /etc/hosts
      - name: docker-ca
        path: /etc/docker
      - name: dockersock
        path: /var/run/docker.sock
    settings:
      username: admin
      password:
        from_secret: harbor_password
      repo: harbor.kubeimooc.com/kubeimooc/kubexcloud
      registry: harbor.kubeimooc.com
      tags:
        - v1.1
  - name: ssh commands
    image: appleboy/drone-ssh
    settings:
      host: 10.0.0.39
      username: root
      password:
        from_secret: ssh_password
      port: 22
      script:
        #拉取镜像并重启 注意--需要提前在目标主机完成docker login
        - if [ $(docker ps -a | grep kubeimooc-server | wc -l) -ge 1 ];then docker stop kubeimooc-server && docker rm kubeimooc-server; fi
        - docker pull harbor.kubeimooc.com/kubeimooc/kubexcloud:v1.1
        - docker run --name kubeimooc-server -d -p8082:8082 harbor.kubeimooc.com/kubeimooc/kubexcloud:v1.1
volumes:
  - name: hosts
    host:
      path: /etc/hosts
  - name: docker-ca
    host:
      path: /etc/docker
  - name: dockersock
    host:
      path: /var/run/docker.sock